<div class="box clearfix">
    <h2>Contact</h2>
    <div class="contact-item">
        <div class="icon pull-left text-center"><span class="fa fa-phone fa-fw"></span></div>
        <div class="title only pull-right">(408) 909-3642</div>
    </div>
    <div class="contact-item">
        <div class="icon pull-left text-center"><span class="fa fa-envelope fa-fw"></span></div>
        <div id="email" class="title only pull-right"></div>
    </div>
    <div class="contact-item">
        <div class="icon pull-left text-center"><span class="fa fa-github fa-fw"></span></div>
        <div class="title pull-right">GitHub</div>
        <div class="description pull-right"><a href="https://github.com/whiteruski">https://github.com/whiteruski</a></div>
    </div>
</div>