<div class="row">
    <div class="col-xs-12">
        <div id="photo-header" class="text-center">
            <!-- PHOTO (AVATAR) -->
            <div id="photo">
                <img src="img/avatar.jpg" alt="avatar">
            </div>
            <div id="text-header">
                <h1>Hello,<br> my name is <span>sushi</span><sup>24yo</sup> and this is my resume/cv</h1>
            </div>
        </div>
    </div>
</div>