<div class="box">
    <h2>About Me</h2>
    <p>A Software Developer located in Phoenix, AZ, with a variety of experience, who picks up new technologies fast and generally learns quickly.</p>
    <p>Seeking a full-time position with a successful company that desires to add a motivated individual to their team of professionals.</p>
    <p>In the past, mostly worked individually or on Agile teams, and have used Git, SVN, and TFS (prefer git though).  Accustomed to efficiently communicating with team members using Slack, HipChat, and in person.</p>
    <p>More details such as company names have been excluded from this public site for privacy reasons, and are available upon request.  Please use the contact information on the right for any inquiries.</p>
</div>