<div class="box">
    <h2>About Me</h2>
    <p>A Software Developer located in Phoenix, AZ, with a variety of experiences, who picks up new technologies fast and generally learns quickly.</p>
    <p>Previously worked both on agile teams or individually, and have used Git, SVN, and TFS (prefer git though).  Accustomed to efficiently communicating with team members using Slack, HipChat, and/or in person.</p>
    <p>More details such as company names have been excluded from this public site for privacy reasons, and are available upon request.  Please use the contact information on the right for any inquiries.</p>
    <p>Currently seeking a position with a successful and growing company that desires to add a motivated individual with a passion for technology and learning to their team of professionals.</p>
    <p>Would prefer a company with a relaxed culture and opportunity for career advancement.</p>
</div>