<div class="box clearfix">
    <h2>Contact</h2>
    <div class="contact-item">
        <div class="icon pull-left text-center"><span class="fa fa-phone fa-fw"></span></div>
        <div class="title only pull-right">(408) 909-3642</div>
    </div>
    <div class="contact-item">
        <div class="icon pull-left text-center"><span class="fa fa-envelope fa-fw"></span></div>
        <div id="email" class="title only pull-right"></div>
    </div>
<!--    <div class="contact-item">-->
<!--        <div class="icon pull-left text-center"><span class="fa fa-twitter fa-fw"></span></div>-->
<!--        <div class="title pull-right">Twitter</div>-->
<!--        <div class="description pull-right">https://twitter.com/WordPress</div>-->
<!--    </div>-->
<!--    <div class="contact-item">-->
<!--        <div class="icon pull-left text-center"><span class="fa fa-facebook fa-fw"></span></div>-->
<!--        <div class="title pull-right">Facebook</div>-->
<!--        <div class="description pull-right">https://www.facebook.com/facebook</div>-->
<!--    </div>-->
<!--    <div class="contact-item">-->
<!--        <div class="icon pull-left text-center"><span class="fa fa-skype fa-fw"></span></div>-->
<!--        <div class="title pull-right">Skype</div>-->
<!--        <div class="description pull-right">kamsolutions.pl</div>-->
<!--    </div>-->
</div>