<div class="box">
    <h2>Education</h2>
    <ul id="education" class="clearfix">
        <li>
            <div class="year pull-left">1990</div>
            <div class="description pull-right">
                <h3>I was born in Katowice</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, exercitationem, totam, dolores iste dolore est aut modi.</p>
            </div>
        </li>
        <li>
            <div class="year pull-left">2005</div>
            <div class="description pull-right">
                <h3>Secondary school specializing in artistic</h3>
                <p>Eos, explicabo, nam, tenetur et ab eius deserunt aspernatur ipsum ducimus quibusdam quis voluptatibus.</p>
            </div>
        </li>
        <li>
            <div class="year pull-left">2009</div>
            <div class="description pull-right">
                <h3>First level graduation in Graphic Design</h3>
                <p>Aspernatur, mollitia, quos maxime eius suscipit sed beatae ducimus quaerat quibusdam perferendis? Iusto, quibusdam asperiores unde repellat.</p>
            </div>
        </li>
        <li>
            <div class="year pull-left">2012</div>
            <div class="description pull-right">
                <h3>Second level graduation in Graphic Design</h3>
                <p>Ducimus, aliquam tempore autem itaque et accusantium!</p>
            </div>
        </li>
    </ul>
</div>