<div class="box">
    <h2>Experiences</h2>
    <div ng-repeat="experience in experiences">
        <div class="job clearfix">
            <div class="col-xs-3">
                <div class="where">{{experience.company}}</div>
                <div class="year">{{experience.time}}</div>
            </div>
            <div class="col-xs-9">
                <div class="profession">{{experience.title}}</div>
                <div class="description">{{experience.description}}</div>
            </div>
        </div>
    </div>
</div>