<div class="box">
    <h2>Skills</h2>
    <div class="skills">
        <div ng-repeat="skill in skills">
            <div class="item-skills" data-percent="{{skill.proficiency}}">{{skill.title}}</div>
        </div>
        <div class="skills-legend clearfix">
            <div class="legend-left legend">None</div>
            <div class="legend-left legend"><span>Beginner</span></div>
            <div class="legend-right legend"><span>Proficient</span></div>
            <div class="legend-right legend">Expert</div>
        </div>
    </div>
</div>