
<div class="col-xs-12 col-sm-7">
    <?php echo $this->partial('partials/about.phtml'); ?>
    <?php echo $this->partial('partials/libraries.phtml'); ?>
    <?php echo $this->partial('partials/experiences.phtml'); ?>
</div>

<div class="col-xs-12 col-sm-5">
    <?php echo $this->partial('partials/contact.phtml'); ?>
    <?php echo $this->partial('partials/skills.phtml'); ?>
    <?php echo $this->partial('partials/languages.phtml'); ?>
    <?php echo $this->partial('partials/hobbies.phtml'); ?>
</div>

